# Generated by Django 5.2.3 on 2025-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopayingg', '0002_alter_debt_options_alter_expense_options_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='0e62b6', max_length=6),
        ),
    ]
