# Generated by Django 5.2.3 on 2025-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopayingg', '0004_alter_otp_token_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default=None, max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('thread_name', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='online_satuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='710003', max_length=6),
        ),
    ]
