# Generated by Django 5.2.3 on 2025-07-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopayingg', '0009_alter_otp_token_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='6ee4ca', max_length=6),
        ),
    ]
