# Generated by Django 5.2.3 on 2025-07-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whopayingg', '0012_alter_otp_token_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='63408c', max_length=6),
        ),
        migrations.CreateModel(
            name='conversation_in_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='whopayingg.group')),
            ],
        ),
        migrations.CreateModel(
            name='Les_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whopayingg.conversation_in_group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
